export enum SocketEventTypes {
  USER_JOIN_TO_ROOM = 'USER_JOIN_TO_ROOM',
  USER_LEAVE_ROOM = 'USER_LEAVE_ROOM',
  UPDATE_MY_CONNECTION_DATA = 'UPDATE__MY_CONNECTION_DATA',
  CALL_USER = 'CALL_USER',
  CALL_MADE = 'CALL_MADE',
  MAKE_ANSWER = 'MAKE_ANSWER',
  ANSWER_MADE = 'ANSWER_MADE'
}
